// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD83TUJtzqeO3LAp2tU68Cd0BWzkM92yTo',
    appId: '1:618618294587:web:66e65d5bb8190355b8a71e',
    messagingSenderId: '618618294587',
    projectId: 'product-db-12bb5',
    authDomain: 'product-db-12bb5.firebaseapp.com',
    databaseURL: 'https://product-db-12bb5-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-12bb5.appspot.com',
    measurementId: 'G-FBHQKCHCQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgUYZg8zNz8wDbKj5mWeTntcktzKklNbY',
    appId: '1:618618294587:android:ef2d598e25e73a4ab8a71e',
    messagingSenderId: '618618294587',
    projectId: 'product-db-12bb5',
    databaseURL: 'https://product-db-12bb5-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-12bb5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOn9lQwnfLCjoVbq_yBJmTApYnkW6nXrI',
    appId: '1:618618294587:ios:e944b7e18a5d9c22b8a71e',
    messagingSenderId: '618618294587',
    projectId: 'product-db-12bb5',
    databaseURL: 'https://product-db-12bb5-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-12bb5.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOn9lQwnfLCjoVbq_yBJmTApYnkW6nXrI',
    appId: '1:618618294587:ios:e944b7e18a5d9c22b8a71e',
    messagingSenderId: '618618294587',
    projectId: 'product-db-12bb5',
    databaseURL: 'https://product-db-12bb5-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-12bb5.appspot.com',
    iosBundleId: 'com.example.product',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD83TUJtzqeO3LAp2tU68Cd0BWzkM92yTo',
    appId: '1:618618294587:web:69da755d2629b496b8a71e',
    messagingSenderId: '618618294587',
    projectId: 'product-db-12bb5',
    authDomain: 'product-db-12bb5.firebaseapp.com',
    databaseURL: 'https://product-db-12bb5-default-rtdb.firebaseio.com',
    storageBucket: 'product-db-12bb5.appspot.com',
    measurementId: 'G-6FX6ERQVWT',
  );
}
